openapi: 3.0.0
info:
  title: Patient Management System - Lab
  version: 1.0.0
paths:
  /lab:
    post:
      summary: Create lab result
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LabResult'
      responses:
        "201":
          description: Lab result created
    get:
      summary: Get all lab results
      security:
        - bearerAuth: []
      responses:
        "200":
          description: List of lab results
          content:
            application/json:
              type: array
              items:
                $ref: '#/components/schemas/LabResult'
  /lab/{id}:
    get:
      summary: Get lab result by ID
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: string }
      responses:
        "200":
          description: Lab result details
    put:
      summary: Update lab result
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LabResult'
      responses:
        "200":
          description: Lab result updated
    delete:
      summary: Delete lab result
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: string }
      responses:
        "204":
          description: Lab result deleted