openapi: 3.0.0
info:
  title: Patient Management System - Visits
  version: 1.0.0
paths:
  /visits:
    post:
      summary: Create a visit
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Visit'
      responses:
        "201":
          description: Visit created
    get:
      summary: Get all visits
      security:
        - bearerAuth: []
      responses:
        "200":
          description: List of visits
          content:
            application/json:
              type: array
              items:
                $ref: '#/components/schemas/Visit'
  /visits/{id}:
    get:
      summary: Get visit by ID
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: string }
      responses:
        "200":
          description: Visit details
    put:
      summary: Update visit
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Visit'
      responses:
        "200":
          description: Visit updated
    delete:
      summary: Delete visit
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: string }
      responses:
        "204":
          description: Visit deleted